name: Ruby

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.4'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Build
      run: gem build baran.gemspec
    - name: Publish
      uses: rubygems/action@v2
      with:
        api_key: ${{ secrets.RUBYGEMS_API_KEY }}
        gem: baran-*.gem
